# Use root/example as user/password credentials
version: '3.1'

services:

  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  # db:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
      
  # web:
  #   image: nginx
  #   volumes:
  #   # - ./ui/dist:/etc/nginx/templates
  #   - ./ui/dist:/usr/share/nginx/html
  #   ports:
  #   - "8080:80"
  #   environment:
  #   - NGINX_HOST=flashcards.com
  #   - NGINX_PORT=80

  web-dev:
    image: node:16
    volumes: 